Python Integration to send raw attacks by cron
vgartvich-wallarm/gke-demo-app-cluster pull request #2
Opened 2020-05-03 08:03 UTC by 416e64726579

Added python integration which fetches raw attacks through Wallarm API and send them to an http collector of Loggly.
The code repo is here https://github.com/416e64726579/Wallarm-API-Client

2020-05-03 15:19 UTC, vgartvich-wallarm requested changes

2020-05-03 15:19 UTC, vgartvich-wallarm commented on terraform/system-apps/log-integration/log-integration/.helmignore
> +# Patterns to ignore when building packages.
Please move the component to new directory terraform/integration-demos/ (please update manage-env.sh as well)

2020-05-03 15:19 UTC, vgartvich-wallarm commented on terraform/system-apps/log-integration/main.tf
> +    value = "awallarm/log-exporter:latest"
Please point to the new repo.

2020-05-03 15:19 UTC, vgartvich-wallarm commented on terraform/system-apps/log-integration/main.tf
> +  set_string {
Please use the existing variable.

2020-05-03 15:19 UTC, vgartvich-wallarm commented on terraform/system-apps/log-integration/main.tf
> +    value = var.loggly_wallarm_uuid
Rename the variable to wallarm_api_uuid.

2020-05-03 15:19 UTC, vgartvich-wallarm commented on terraform/system-apps/log-integration/main.tf
> +    value = var.loggly_wallarm_secret
Rename the variable to wallarm_api_secret.

2020-05-04 07:45 UTC, 416e64726579 commented
Please, take a glance at the latest commit. I've fixed all discussed.

2020-05-04 14:45 UTC, merged